### PR TITLE
Fix medium code quality from DeepScan and remove ESlint exceptions

### LINKED ISSUE #1988: Fix medium DeepScan Code quality issues
See https://deepscan.io/dashboard/#view=project&tid=616&pid=1475&bid=4666&subview=issues&impact=%5B%22Medium%22%5D&page=1

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #1988

**WARNING:** This removes the possibility of switching from a uncontrolled `defaultValue` in form elements to a controlled `value`. Consumers should never be doing this without unmounting components first, but it's possible if consumers are switching between uncontrolled and controlled components that this will break their applications. See https://reactjs.org/docs/uncontrolled-components.html

This PR adds the following code to input elements:
```
/* A form element should not have both checked and defaultChecked props. */
{...(this.props.defaultChecked
	? { defaultChecked: this.props.defaultChecked }
	: { checked: this.props.checked })}
```

See https://deepscan.io/dashboard/#view=project&tid=616&pid=1475&bid=4666&subview=issues&impact=%5B%22Medium%22%5D&page=1

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/input/private/inner-input.jsx [hunk 1]
```diff
@@ -297,8 +297,10 @@ const InnerInput = (props) => {
 					style={props.style}
 					tabIndex={props.tabIndex}
 					type={props.type}
-					value={props.value}
-					defaultValue={props.defaultValue}
+					/* A form element should not have both value and defaultValue props. */
+					{...(props.defaultValue
```
Comment (kevinparkerson) [inline components/input/private/inner-input.jsx]: should this check for `props.defaultValue !== undefined` to ensure falsey (but intended) values are passed along?

Comment (kevinparkerson) [reply components/input/private/inner-input.jsx]: also should this prioritize `(props.value)` over `(props.defaultValue)`?

File: components/radio/index.jsx [hunk 2]
```diff
@@ -155,8 +155,10 @@ class Radio extends React.Component {
 					id={this.getId()}
 					name={this.props.name}
 					value={this.props.value}
-					checked={this.props.checked}
-					defaultChecked={this.props.defaultChecked}
+					/* A form element should not have both checked and defaultChecked props. */
+					{...(this.props.defaultChecked
```
Comment (kevinparkerson) [inline components/radio/index.jsx]: same with value, perhaps the condition should look for `!== undefined`, and prioritizing `checked` over `defaultChecked`

File: components/slider/index.jsx [hunk 3]
```diff
@@ -195,15 +195,17 @@ class Slider extends React.Component {
...
 							min={this.props.min}
 							max={this.props.max}
 							step={this.props.step}
 							aria-describedby={this.getErrorId()}
-							value={this.props.value}
 							disabled={this.props.disabled}
 							onChange={this.handleChange}
 							onInput={this.handleInput}
+							/* A form element should not have both value and defaultValue props. */
+							{...(this.props.defaultValue
```
Comment (kevinparkerson) [inline components/slider/index.jsx]: same as others
