### PR TITLE
Accessibility audit fixes for Combobox, DataTable, Expression, Map, and Dropdown

### LINKED ISSUE #2358: Fix accessibility issues from audit for Combobox, DataTable, Expression, Map, and Dropdown
- Combobox: Headers/footers need to read properly and most recent item should be immediate previous tab index after selection
- Data Table: aria-live needs to be removed, checkbox names need to be unique
- Expression: focus needs to move to first input upon adding new condition or group
- Map: focus needs to move to map when selecting a location
- Menu Dropdown: styling needs to be corrected for header text orientation

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #2358

* [x] Combobox: Headers/footers need to read properly and most recent item should be immediate previous tab index after selection
* [x] DataTable: aria-live needs to be removed, checkbox names need to be unique
* [x] Expression: focus needs to move to first input upon adding new condition or group
* [ ] Map: focus needs to move to map when selecting a location
* [x] Menu Dropdown: styling needs to be corrected for header text orientation

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
I'm going to go ahead and merge this. `Map: focus needs to move to map when selecting a location` should be working based on the code, but I'm not hearing the iframe's title read in VoiceOver (for instance).

File: components/combobox/combobox.jsx [hunk 1]
```diff
@@ -472,6 +472,22 @@ class Combobox extends React.Component {
 				activeSelectedOptionIndex: 0,
 			});
 		}
+
```
Comment (interactivellama) [inline components/combobox/combobox.jsx]: Great solution!

**Comment by kevinparkerson** [comment]
@interactivellama VoiceOver is behaving really inconsistently; the first time you load the page, tabbing to it will put a box around it and it reads "frame 1, Salesforce Locations In United States, group". Shift tab and then tab back to it, it reads "group, Salesforce Locations In United States, group" with no box around it. Additionally both times there's a period where it says "Chrome busy" before it does anything. Additionally, the iframe never shows a visual indicator of being tabbed on without some sort of screen reader being activated. There are two solutions I can see for this:

1.) inject styling that makes the iframe have a highlight when focused like most normal elements do
2.) change the focusable element to the `.slds-map` div. We'd also need to move the `title` prop to that element so it'd read correctly. This diverges from SLDS markup a bit though

Let me know what you think, I can try to address this in a separate PR
