### PR TITLE
Colorpicker a11y fixes

### LINKED ISSUE #2014: Colorpicker: ARIA attribute must conform to valid value
https://design-system-react-co-pr-2004.herokuapp.com/?selectedKind=SLDSColorPicker&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Issue: Automated aXe test fails ARIA attribute. 
expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#color-picker-summary-input-default-color-picker') to have no violations:

   ` <input aria-describedby="color-picker-summary-error-default-color-picker" class="slds-input" id="color-picker-summary-input-default-color-picker" type="text" value="">`

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

This is most likely due to the ID that is being pointed to not being on the page when the markup audit occurs. The solution is to only add the ID when the menu/popover is on the page. This typically done through a conditional called isOpen.

Solution: See https://github.com/salesforce/design-system-react/pull/2004 as possible solution.

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #2014

Also fixes tabs accessibility issues out of necessity

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/tabs/index.jsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ import EventUtil from '../../utilities/event';
 function isTabNode(node) {
 	return (
 		(node.nodeName === 'A' && node.getAttribute('role') === 'tab') ||
-		(node.nodeName === 'LI' && node.getAttribute('role') === 'tab')
+		(node.nodeName === 'LI' && node.getAttribute('role') === 'presentation')
```
Comment (minevskiy) [inline components/tabs/index.jsx]: This is a very broad check. Would be better to check for classes. 
This check is true for some of our content within a tab. If I click on node at position N within the content, the tab at position N becomes active.

Comment (interactivellama) [reply components/tabs/index.jsx]: Good catch. `tab` is what we were looking but `presentation` gets used often in SLDS.
