### PR TITLE
Data table fixed header scrolling bugfix

### LINKED ISSUE #1696: DataTable: Scroll/render bug on tab
Tabbing between the headers creates this bug when the table is hidden. It happens in Chrome and FireFox. Tabbing between items in the actual table data does not create this bug

screen shot 2018-12-20 at 5 09 46 pm

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #1696

This was an interesting bug! When tabbing and therefore focusing on headers outside the visible area the browser has to make a decision on how to bring them into view, which apparently defaults to "scroll the parent container." Since the headers are absolutely positioned as far as the rendering engine is concerned that parent is `.slds-table_header-fixed_container` rather than the table header that actually contains them. The browser then "scrolls" that parent left by an arbitrary amount in order to bring the focused element into view. Since `.slds-table_header-fixed_container` actually has `overflow: hidden` no scrollbar is shown, and `.slds-table_header-fixed_scroller` appears "clipped" because it is retaining the actual width of the parent container as it is scrolled left to reveal the hidden content. The effect looks quite goofy but it actually makes sense once you understand what's going on!

I tried a few different approaches to fixing this bug such as making the container have `overflow-x: auto` and the scroller `overflow-y: auto`, but that introduced other visual bugs. The simplest, most elegant solution I found was to add an `onScroll` event to the container that sets its scrollLeft value to a variable and checks if it surpasses 0. If so, the container's scrollLeft is reset to 0. Since both the container and scroller share the same width, the pre-reset scrollLeft value can then be applied to the scroller itself and effectively bring the focused content into view. The scroller's listeners then kick in and make sure to reposition / resize the headers correctly as expected, and everything looks as it should!

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/data-table/index.jsx [hunk 1]
```diff
@@ -316,14 +316,10 @@ class DataTable extends React.Component {
 					}
 
 					const cellFixed = column.querySelector('.slds-cell-fixed');
-					const linkFixed = cellFixed.firstChild;
 
 					if (cellFixed) {
 						cellFixed.style.left = `${columnLeft - wrapperLeft}px`;
-					}
-
-					if (linkFixed) {
```
Comment (kevinparkerson) [inline components/data-table/index.jsx]: @interactivellama why was this altered? I had styles to make headers fill the cellFixed element provided it was properly sized. If there was something I missed I would prefer to add `width: 100%` to whatever it was and only resize the cellFixed element rather than attempt to size it's immediate child manually in this way

File: components/data-table/__examples__/fixed-header.jsx [hunk 2]
```diff
@@ -204,9 +204,10 @@ class Example extends React.Component {
 			<div
 				style={{
 					height: '200px',
-					width: '100%',
+					width: '800px',
 				}}
 			>
+				<style dangerouslySetInnerHTML={{ __html: '.dsr_data-table-fixed-header-scroll-test { width: 1600px; }' }} />
```
Comment (kevinparkerson) [inline components/data-table/__examples__/fixed-header.jsx]: @interactivellama this was added for testing... do we want to leave this stuff in there and make a vertical / horizontal fixed header story example the default that shows up on the site? Or should I make another example with horizontal scrolling in order to preserve the simpler vertical-only scrolling fixed header example?

Comment (interactivellama) [reply components/data-table/__examples__/fixed-header.jsx]: I'd lean toward another story, although if we can just pass in a prop that modifies the same story, that'd probably be best.

File: components/data-table/index.jsx (hunk 1 above)
Comment (interactivellama) [reply components/data-table/index.jsx]: I believe the value was null in the radio group variant which resulted in a key call on an undefined object.

https://github.com/salesforce/design-system-react/issues/1708

File: components/data-table/index.jsx [hunk 3]
```diff
@@ -517,6 +513,16 @@ class DataTable extends React.Component {
 				<div
 					className="slds-table_header-fixed_container"
 					style={{ height: '100%' }}
+					onScroll={(e) => {
```
Comment (interactivellama) [inline components/data-table/index.jsx]: Can we add more conditions to this? Maybe something like if horizontal scrolling can occur (that is something like measuring `clientWidth`?).

File: components/data-table/index.jsx (hunk 1 above)
Comment (kevinparkerson) [reply components/data-table/index.jsx]: Resolved via meeting

File: components/data-table/__examples__/fixed-header.jsx (hunk 2 above)
Comment (kevinparkerson) [reply components/data-table/__examples__/fixed-header.jsx]: @kevinparkerson: create a `style` prop that gets applied to the table. Create a separate fixed header horizontal story that demonstrates horizontal scrolling without adding it to doc site. Update doc site to refer to using `style` prop to obtain horizontal scrolling (have a note in `style` prop description and a note in the top description of the component referencing the `style` prop)

**Comment by kevinparkerson** [comment]
@interactivellama this is ready for re-review
