### PR TITLE
Combobox: ARIA attribute fixes

### LINKED ISSUE #2003: Combobox: ARIA attributes are invalid
Fix the following issues in Combobox:

```
FAIL  tests/story-based-accessibility-tests.js (41.016s)
  aXe Testing
    aXe storyshots
      SLDSCombobox
        ✕ Base (1564ms)
        ✕ Base Pre-defined Options Only (1223ms)
        ✕ Base Inline Help (1381ms)
        ✕ Base Menu Item Disabled (1105ms)
        ✕ Base Menu Item Disabled With Tooltip (1100ms)
        ✕ Base Menu Item Disabled With Tooltip Open (3441ms)
        ✕ Inline Single Selection (259ms)
        ✕ Inline Multiple Selection (1143ms)
        ✕ Base Custom Menu Item (261ms)
        ✕ Base Custom Menu Item Disabled (261ms)
        ✕ Base Menu Sub Headers (258ms)
        ✕ Base Menu Separator (260ms)
        ✕ Base Inherit Menu Width (257ms)
        ✓ Dialog (298ms)
        ✕ Readonly Single Selection (292ms)
        ✕ Readonly Single Selection Disabled (258ms)
        ✕ Readonly Single Menu Item Disabled (279ms)
        ✕ Readonly Multiple Selection (277ms)
        ✕ Readonly Single Selection Custom Menu Item (282ms)
        ✕ Required Input in Error State (314ms)
        ✕ Input Component as a Prop (1078ms)
        ✕ Snapshot Base Open (1044ms)
        ✕ Snapshot Base Custom Menu Item Open (2091ms)
        ✕ Snapshot Base Selected (698ms)
        ✕ Snapshot Base Label Required (338ms)
        ✕ Snapshot Base Open Menu Sub Header Separator (651ms)
        ✕ Snapshot Base Open Menu inheritWidthOf prop (660ms)
        ✕ Snapshot Dialog Open (815ms)
        ✕ Snapshot Inline Single Selection (288ms)
        ✕ Snapshot Inline Single Selection Selected (397ms)
        ✕ Snapshot Inline Multiple Selection (268ms)
        ✕ Snapshot Inline Multiple Selection Selected (1145ms)
        ✕ Snapshot Readonly Single Selection (282ms)
        ✕ Snapshot Readonly Single Selection Disabled (265ms)
        ✕ Snapshot Readonly Single Selection Selected (271ms)
        ✕ Snapshot Readonly Single Selection Selected Open (2536ms)
        ✕ Snapshot Readonly Multiple Selection (269ms)
        ✕ Snapshot Readonly Multiple Selection Single Item Selected (270ms)
        ✕ Snapshot Readonly Multiple Selection Multiple Items Selected (900ms)
        ✕ Snapshot Readonly Single Selection Custom Menu Item (3824ms)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Pre-defined Options Only

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-predefined-options-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-predefined-options') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-predefined-options-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-predefined-options" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Inline Help

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('button') to have no violations:

    <button class="slds-button slds-button_icon" type="button" aria-disabled="true" aria-describedby="field-level-help-tooltip">

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-inline-help-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-inline-help') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-inline-help-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-inline-help" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Menu Item Disabled

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Menu Item Disabled With Tooltip

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Menu Item Disabled With Tooltip Open

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-base-listbox') to have no violations:

    <section class="absolute-positioned" style="outline: 0; position: absolute; pointer-events: none; width: 0px;" role="listbox" id="combobox-base-listbox">

    Expected the HTML found at $('#combobox-base-listbox-option-help-4') to have no violations:

    <section class="absolute-positioned slds-nubbin_bottom slds-popover slds-popover_tooltip" style="outline: 0; position: absolute; pointer-events: none;" role="tooltip" id="combobox-base-listbox-option-help-4">

    Expected the HTML found at $('#combobox-base-listbox-option-help-6') to have no violations:

    <section class="absolute-positioned slds-nubbin_bottom slds-popover slds-popover_tooltip" style="outline: 0; position: absolute; pointer-events: none;" role="tooltip" id="combobox-base-listbox-option-help-6">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Inline Single Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-inline-single') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-inline-single-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-inline-single" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Inline Multiple Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-inline-multiple') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-inline-multiple-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-inline-multiple" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Custom Menu Item

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-custom-menu-item-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-custom-menu-item') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-custom-menu-item-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-custom-menu-item" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Custom Menu Item Disabled

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-unique-id-listbox" role="combobox">

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Menu Sub Headers

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-menu-subheader-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-menu-subheader') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-menu-subheader-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-menu-subheader" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Menu Separator

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-menu-separator-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-menu-separator') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-menu-separator-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-menu-separator" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Base Inherit Menu Width

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-base-inherit-menu-width-listbox" role="combobox">

    Expected the HTML found at $('#combobox-base-inherit-menu-width') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-base-inherit-menu-width-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-base-inherit-menu-width" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Readonly Single Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-readonly-single') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-readonly-single-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-readonly-single" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Readonly Single Selection Disabled

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" disabled="" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Readonly Single Menu Item Disabled

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-readonly-single') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-readonly-single-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-readonly-single" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Readonly Multiple Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-readonly-multiple') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-readonly-multiple-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-readonly-multiple" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Readonly Single Selection Custom Menu Item

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-readonly-single-custom-item') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-readonly-single-custom-item-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-readonly-single-custom-item" placeholder="Select company" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Required Input in Error State

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside slds-has-error" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-required-error-state-listbox" role="combobox">

    Expected the HTML found at $('#combobox-required-error-state') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-required-error-state-listbox" aria-describedby="description-unique-id" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-required-error-state" placeholder="Search Salesforce" required="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Input Component as a Prop

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-input-prop-example-listbox" role="combobox">

    Expected the HTML found at $('#id_from_input_prop') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-input-prop-example-listbox" autocomplete="test" class="slds-input slds-combobox__input" id="id_from_input_prop" placeholder="My overridden placeholder" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

    ────────

    Expected the HTML found at $('#id_from_input_prop') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-input-prop-example-listbox" autocomplete="test" class="slds-input slds-combobox__input" id="id_from_input_prop" placeholder="My overridden placeholder" role="textbox" type="text" value="">

    Received:

    "autocomplete attribute must be used correctly (autocomplete-valid)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/autocomplete-valid?application=axeAPI

    ────────

    Expected the HTML found at $('#id_from_input_prop') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-input-prop-example-listbox" autocomplete="test" class="slds-input slds-combobox__input" id="id_from_input_prop" placeholder="My overridden placeholder" role="textbox" type="text" value="">

    Received:

    "Form elements must have labels (label)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/label?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Open

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-unique-id-listbox') to have no violations:

    <section role="listbox" id="combobox-unique-id-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Custom Menu Item Open

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-base-custom-menu-item-listbox') to have no violations:

    <section role="listbox" id="combobox-base-custom-menu-item-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-unique-id-listbox" role="combobox">

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "Form elements must have labels (label)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/label?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Label Required

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside slds-has-error" aria-expanded="false" aria-haspopup="listbox" aria-owns="combobox-required-error-state-listbox" role="combobox">

    Expected the HTML found at $('#combobox-required-error-state') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-required-error-state-listbox" aria-describedby="description-unique-id" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-required-error-state" placeholder="Search Salesforce" required="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Open Menu Sub Header Separator

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-unique-id-listbox') to have no violations:

    <section role="listbox" id="combobox-unique-id-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Base Open Menu inheritWidthOf prop

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-unique-id-listbox') to have no violations:

    <section role="listbox" id="combobox-unique-id-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Dialog Open

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox') to have no violations:

    <div class="slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click ignore-react-onclickoutside slds-is-open" aria-expanded="true" aria-haspopup="dialog" aria-owns="combobox-unique-id" role="combobox">

    Received:

    "Certain ARIA roles must contain particular children (aria-required-children)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-required-children?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Inline Single Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Inline Single Selection Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" readonly="" role="textbox" type="text" value="Acme">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Inline Multiple Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Inline Multiple Selection Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Search Salesforce" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Single Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Single Selection Disabled

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" disabled="" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Single Selection Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="Acme">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Single Selection Selected Open

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="true" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id-listbox') to have no violations:

    <section role="listbox" id="combobox-unique-id-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Multiple Selection

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Multiple Selection Single Item Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="Acme">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Multiple Selection Multiple Items Selected

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="false" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-unique-id') to have no violations:

    <input aria-autocomplete="list" aria-controls="combobox-unique-id-listbox" autocomplete="off" class="slds-input slds-combobox__input" id="combobox-unique-id" placeholder="Select an Option" readonly="" role="textbox" type="text" value="2 options selected">

    Received:

    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-valid-attr-value?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

  ● aXe Testing › aXe storyshots › SLDSCombobox › Snapshot Readonly Single Selection Custom Menu Item

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-combobox__form-element') to have no violations:

    <div class="slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right" aria-expanded="true" aria-haspopup="listbox" role="none">

    Received:

    "Elements must only use allowed ARIA attributes (aria-allowed-attr)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-attr?application=axeAPI

    ────────

    Expected the HTML found at $('#combobox-readonly-single-custom-item-listbox') to have no violations:

    <section role="listbox" id="combobox-readonly-single-custom-item-listbox" style="width: 0px;">

    Received:

    "ARIA role must be appropriate for the element (aria-allowed-role)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=axeAPI

      65 | 			const component = story.render(context);
      66 | 			const wrapper = mount(component);
    > 67 | 			expect(await axe(wrapper.html())).toHaveNoViolations();
         | 			                                  ^
      68 | 		},
      69 | 	});
      70 | });

      at _callee$ (story-based-accessibility-tests.js:67:38)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (story-based-accessibility-tests.js:395:103)
      at _next (story-based-accessibility-tests.js:397:194)

```

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #2003

### Additional description
This allows aXe audit to pass for Combobox. `npm run test:a11y`
@jcjuett @kevinparkerson 

Screen Shot 2019-05-31 at 9 32 26 AM

@aswinshenoy @pulkonet When you run `npm run test:a11y` on your new work (and you should! -- but it is not currently in the TravisCI tasks list for all pull requests today). This PR may help with fixing some of the errors.

The issues were duplicate ARIA attributes used when only one was set was needed and that HTML IDs were being referenced when they were not on the page, since it's React convention to only add visible HTML nodes to the page such as when displaying menus, popovers, and tooltips.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
@kevinparkerson Do the combobox a11y tests pass?

**Comment by interactivellama** [comment]
You will need to do an `npm install` due to the axe fork I made

**Comment by interactivellama** [comment]
@kevinparkerson Updated

File: components/combobox/__examples__/input-prop.jsx [hunk 1]
```diff
@@ -79,8 +79,8 @@ class Example extends React.Component {
 		// example of passing in an SLDSInput component to a SLDSCombobox
 		const inputElement = (
 			<Input
+				label="Search"
 				autoComplete="test"
-				id="id_from_input_prop"
```
Comment (kevinparkerson) [inline components/combobox/__examples__/input-prop.jsx]: @interactivellama why was this id removed? not needed for snapshot testing?

**Comment by kevinparkerson** [comment]
@interactivellama still seeing this locally:
Screen Shot 2019-06-19 at 3 25 25 PM

File: components/combobox/__examples__/input-prop.jsx (hunk 1 above)
Comment (interactivellama) [reply components/combobox/__examples__/input-prop.jsx]: Yes, it was not needed.

**Comment by kevinparkerson** [comment]
Screen Shot 2019-06-19 at 3 28 47 PM
