### PR TITLE
Color Picker: Fixing bug when transparent swatch cannot be set

### LINKED ISSUE #1615: Color picker: setting transparent as value or working value prop doesn't work
I introduced a bug where setting transparent as value or workingValue doesn't work.

I will create a PR to fix it, thanks.

### PR DESCRIPTION
**Pull request by davidlygagnon**
Fixes #1615 and #1612

### Additional description

Fixing bug in ColorPicker component where transparent cannot be set.
Adding `assistiveText.label` and `checkProps` warning to choose between `assistiveText.label` or `labels.label`

--- 

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/color-picker/__docs__/storybook-stories.jsx [hunk 1]
```diff
@@ -117,6 +117,7 @@ storiesOf(COLOR_PICKER, module)
 			errorTextWorkingColor="Hex is invalid. Please correct this field."
 			id="working-color-error-state-color-picker"
 			labels={{ label: 'Choose Color' }}
+			valueWorking="#f"
```
Comment (davidlygagnon) [inline components/color-picker/__docs__/storybook-stories.jsx]: Story showing error message on working color should use an invalid color for better representation.

File: components/color-picker/index.jsx [hunk 2]
```diff
@@ -240,14 +244,12 @@ class ColorPicker extends React.Component {
 		const workingColor = ColorUtils.getNewColor(
 			{
 				hex:
-					this.props.valueWorking ||
-					this.props.value ||
-					this.props.swatchColors[0],
+					this.props.valueWorking || this.props.value || '#000000'
```
Comment (davidlygagnon) [inline components/color-picker/index.jsx]: The working color should never be transparent, so I am intentionally setting black as default color if transparent is selected. Otherwise, we get in this kind of situation
screen shot 2018-10-24 at 1 18 26 am.

File: components/color-picker/private/swatch-picker.jsx [hunk 3]
```diff
@@ -92,20 +93,16 @@ class SwatchPicker extends React.Component {
...
-					);
-				})}
+				{this.props.swatchColors.map((color, index) => (
+					<SwatchOption
+						color={color}
+						key={color}
+						onSelect={this.props.onSelect}
+						swatchOptionRef={this.addRef(color)}
+						workingColor={this.props.color}
+						tabIndex={(this.props.color && this.props.color.hex === color) || (index === 0 && !isSelectedColorInSwatch) ? 0 : -1}
```
Comment (davidlygagnon) [inline components/color-picker/private/swatch-picker.jsx]: tabIndex of swatch option will be 0 if it's the currently selected color (so that we can tab back right into it) or if it's the first swatch option and the color is not in the set of colors (so that we can tab into the first swatch option).
