### PR TITLE
DataTable: Add top border to fixed header tables

### LINKED ISSUE #1753: DataTable: Missing top border in Fixed Header
Fixed Header DataTable is missing a top border.

screen shot 2019-02-18 at 3 47 18 pm

We removed the top border, because of the fixed header being moved up. The SLDS border styling creates a double border, so we removed it, but forgot to add it to the container.

screen shot 2019-02-18 at 3 51 31 pm

http://design-system-react-components.herokuapp.com/?selectedKind=SLDSDataTable&selectedStory=Fixed%20Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #1753

Making data table look correct when headers are fixed

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/data-table/index.jsx [hunk 1]
```diff
@@ -516,7 +516,7 @@ class DataTable extends React.Component {
 			component = (
 				<div
 					className="slds-table_header-fixed_container"
-					style={{ height: '100%' }}
+					style={{ borderTop: '1px solid #dddbda', height: '100%' }}
```
Comment (interactivellama) [inline components/data-table/index.jsx]: Please use design token $color-gray-5
https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#use-design-tokens-for-inline-styles

Example: https://github.com/salesforce/design-system-react/blob/master/components/global-navigation-bar/dropdown-trigger.jsx#L145

**Comment by kevinparkerson** [comment]
@interactivellama this is ready for re-review
