### PR TITLE
Card: add hasNoHeader prop

### LINKED ISSUE #1581: Missing Card without header
On the `<Card>` component the Header is not optional. I often use Cards for tables below a `<PageHeader>` where the Card Header might be redundant in some cases (depending on the Page).

Would you consider to make the Card header optional or are there other ways to put a Border and Background around my table?

One workaround might be:
`slds-box  slds-theme_default` which would give the border and background, but adds too much padding and adding an additional `style={{"padding":0, "border-top":"0px"}}` feels wrong.

### PR DESCRIPTION
**Pull request by pulkonet**
Fixes #1581 
Hi @interactivellama  @futuremint, I have added the requested `hasNoHeader` prop.

### Additional description

Adds hasNoHeader prop to the card component 

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by pulkonet** [comment]
@interactivellama Hello, the travis-ci is passing the tests on my machine but failing here, can you help me with this?

**Comment by pulkonet** [comment]
@futuremint @interactivellama please provide your thoughts so that I can work on other features with those in mind.

**Comment by interactivellama** [comment]
`hasNoHeader` is inline with codebase docs.  👍  Quick glance looks good. I'll add this to my review backlog for deeper review.

If you want, you can probably just use Jest DOM snapshot testing and not any Mocha testing since the non header variant isn't interactive and just rendered DOM.

File: components/card/index.jsx [hunk 1]
```diff
@@ -118,6 +120,10 @@ Card.propTypes = {
 	 * Footer often contains pagination.
 	 */
 	footer: PropTypes.node,
+	/**
+	 * Allows card to have no header.
+	 */
+	hasNoHeader: PropTypes.bool,
```
Comment (davidlygagnon) [inline components/card/index.jsx]: Should we try to keep prop names in the positive form, `hasHeader` and set it default to `true`? If not, maybe `forceNoHeader` might better explain this prop since it's really overriding `props.header` and forcing the component to not have a custom or default header.

Comment (interactivellama) [reply components/card/index.jsx]: No truthy defaults: https://github.com/salesforce/design-system-react/blob/master/docs/codebase-overview.md#no-truthy-defaults-for-boolean-type-props

Maybe we could add to the comment that it ignores `props.header` and other props?

Comment (davidlygagnon) [reply components/card/index.jsx]: ah ok - good stuff about no truthy defaults. Yes, adding a comment on the prop will help.  I wanted to avoid naming props in the negative form so we don't end up with double negation like `hasNoHeader=false` but I guess that's ok. 

It would have been nice to just have `prop.header` to control the header but things get more complicated when we want to have the option of a default header. Cool! Let's leave as is and add a comment.

Comment (pulkonet) [reply components/card/index.jsx]: I have added suggested prop description to the comment. @interactivellama please check.
