### PR TITLE
Make Slider a controlled component

### LINKED ISSUE #1398: Slider: Allow value to be set
Currently Slider doesn't set the `value` of the input, and therefore cannot be a controlled component. This means it just doesn't work.

The following should work, but since the value attribute of `input` doesn't ever change `onChange` is never fired.

```
const DemoSlider = createReactClass({
	displayName: 'DemoSlider',

	getInitialState () {
		return {
			value: this.props.value,
		};
	},

	handleChange (event, { value }) {
		this.setState({ value: parseInt(value, 10) });
	},

	render () {
		return (
			<Slider
				{...this.props}
				value={this.state.value}
				onChange={this.handleChange}
			/>
		);
	},
});

const Example = createReactClass({
	displayName: 'SliderExample',

	render () {
		return (
			<section>
				<ol>
					<li className="slds-p-bottom--large">
						<h1 className="slds-text-title_caps slds-p-vertical--medium">
							1. Base Input with label
						</h1>
						<DemoSlider id="base-id" label="My Label" value={50} />
					</li>
				</ol>
			</section>
		);
	},
});

export default Example;

```

### PR DESCRIPTION
**Pull request by DanFerro**
Now sets the value attribute from props.value.

Fixes #1398

---

### Pull Request Review checklist (do not remove)

* [x] `npm run lint:fix` has been run and linting passes.
* [X] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
@garygong This was the question I was asking about earlier that was whether a change to a component was a breaking change if the component did not work as intended in the first place.

**Comment by interactivellama** [comment]
Moving Review request to @futuremint if he is available this week.

**Comment by futuremint** [comment]
I'm available and I'll review this today.

File: components/slider/index.jsx [hunk 1]
```diff
@@ -140,13 +139,13 @@ class Slider extends React.Component {
 
 	handleChange = (event) => {
 		if (isFunction(this.props.onChange)) {
-			this.props.onChange(event, { value: event.target.value });
+			this.props.onChange(event, { value: parseInt(event.target.value, 10) });
```
Comment (futuremint) [inline components/slider/index.jsx]: This could pose a problem should a user want to make a slider for floats (a slider between 0 and 1 for example).  I'm not sure we want to have `parseInt` here because we can't assume.

File: components/utilities/dialog/index.jsx [hunk 2]
```diff
@@ -400,7 +400,7 @@ const Dialog = createReactClass({
 		}
 
 		if (this.props.style) {
-			style = Object.assign(style, this.props.style);
+			style = { ...style, ...this.props.style };
```
Comment (futuremint) [inline components/utilities/dialog/index.jsx]: 👍

File: utilities/warning/url-exists.js [hunk 3]
```diff
@@ -13,32 +13,43 @@ if (process.env.NODE_ENV !== 'production') {
...
-				const additionalComment = comment ? ` ${comment}` : '';
-				/* eslint-disable max-len */
-				warning(
-					!url,
-					`The icon asset was not found at ${url}. Make sure the path to the icon asset is correct. You can set the icon path by importing the IconSettings component, \`<IconSettings iconPath=[/assets/icons]>\` from \`components/iconSettings\`, and wrap that component around your entire app or around individual components using icons. If you are using the \`<Icon>\` component, you can also pass the url to \`this.props.path\`.${additionalComment}`
-				);
-				/* eslint-enable max-len */
-				hasWarned[`${control}-path`] = !!url;
-			}
+	const warn = (control, url, comment) => (res) => {
```
Comment (futuremint) [inline utilities/warning/url-exists.js]: Is there a reason to add support for `fetch` here? Does this address a maintenance issue in the backlog or something else?

File: components/slider/index.jsx (hunk 1 above)
Comment (interactivellama) [reply components/slider/index.jsx]: value return text, but we expect number be passed in. I'll look into using `Number()`.

**Comment by interactivellama** [comment]
@futuremint 
* Fetch commit removed after pull from upstream.
* `parseInt` replaced with `Number()`
