### PR TITLE
Data Table header cell markup fixes

### LINKED ISSUE #1352: Error  'Warning: Received `true` for a non-boolean attribute `focusable`
I get the following Error in the console when I use a DataTable. 
Version: 0.8.14

```
Warning: Received `true` for a non-boolean attribute `focusable`.

If you want to write it to the DOM, pass a string instead: focusable="true" or focusable={value.toString()}.
    in th (created by SLDSDataTableHeaderCell)
    in SLDSDataTableHeaderCell (created by SLDSDataTableHead)
    in tr (created by SLDSDataTableHead)
    in thead (created by SLDSDataTableHead)
    in SLDSDataTableHead (created by SLDSDataTable)
    in table (created by SLDSDataTable)
    in SLDSDataTable (created by JobsTable)
    in SLDSIconSettings (created by JobsTable)
    in div (created by JobsTable)
    in JobsTable (created by JobsListView)
    in SLDSIconSettings (created by JobsListView)
    in div (created by JobsListView)
    in JobsListView (created by ZincJobs)
    in ZincJobs (created by UserIsAuthenticated(ZincJobs))
    in UserIsAuthenticated(ZincJobs) (created by Connect(UserIsAuthenticated(ZincJobs)))
    in Connect(UserIsAuthenticated(ZincJobs)) (created by withSaga(Connect(UserIsAuthenticated(ZincJobs))))
    in withSaga(Connect(UserIsAuthenticated(ZincJobs))) (created by withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs)))))
    in withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs)))) (created by Connect(withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs))))))
    in Connect(withReducer(withSaga(Connect(UserIsAuthenticated(ZincJobs))))) (created by Route)
    in Route (created by RouteWithLayout)
    in div (created by PageBase)
    in div (created by PageBase)
    in div (created by PageBase)
    in div (created by PageBase)
    in PageBase (created by RouteWithLayout)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in MuiThemeProvider (created by Layout)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Route)
    in Route (created by withRouter(WithWidth))
    in withRouter(WithWidth) (created by Connect(withRouter(WithWidth)))
    in Connect(withRouter(WithWidth)) (created by RouteWithLayout)
    in RouteWithLayout (created by App)
    in Switch (created by App)
    in div (created by App)
    in Router (created by App)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App) (created by Connect(withRouter(App)))
    in Connect(withRouter(App))
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
```

### LINKED ISSUE #1384: DataTable Header cells not aligned and padding is wrong
http://design-system-react-components.herokuapp.com/?selectedKind=SLDSDataTable&selectedStory=Advanced%20%28Fixed%20Layout%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

screen shot 2018-05-16 at 5 18 55 pm

While in the `DataTable` code to fix #1352. I notices that the header cell for Advanced DataTable Header cells not aligned and padding is wrong.

According to our analytics DataTable is the most viewed component on the doc site.

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #1384. Fixes #1352.

## Additional description

Advanced DataTable assumes that you can resize and sort all columns. This aligns DSR DataTable to [SLDS visually](https://www.lightningdesignsystem.com/components/data-tables/).

### DSR:
screen shot 2018-05-16 at 11 33 49 pm

### SLDS
screen shot 2018-05-16 at 11 34 03 pm

### Task
* Updates classes to new BEM (`_` instead of `—`)
* Updates `assistiveTextForColumnSort` to `Sort by: `
* Add `slds-table_resizable-cols` to `<table>` for CSS rules
* Adds ~inline padding override of 0 to header cells that are sortable and~ `slds-p-horizontal_x-small` to cells that not sortable.
* Moves `slds-text-title_caps` down to cell level to match Advanced variant
* Adds `ariaSort=“none”`
* Adds `aria-label` if column label is a string
* Adds visual regressions in order to prevent header size issue and alignment in the future

---

### Pull Request Review checklist (do not remove)

* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/data-table/private/header-cell.jsx [hunk 1]
```diff
@@ -122,26 +122,36 @@ const DataTableHeaderCell = createReactClass({
 		const sortDirection = this.props.sortDirection || this.state.sortDirection;
 		const expandedSortDirection =
 			sortDirection === 'desc' ? 'descending' : 'ascending';
-		const ariaSort = isSorted ? expandedSortDirection : null;
```
Comment (ivanbogdanov) [inline components/data-table/private/header-cell.jsx]: 👍

File: components/data-table/private/header-cell.jsx [hunk 2]
```diff
@@ -122,26 +122,36 @@ const DataTableHeaderCell = createReactClass({
...
+		const ariaSort = isSorted ? expandedSortDirection : 'none';
+		// The following padding styles exist in case you have
```
Comment (garygong) [inline components/data-table/private/header-cell.jsx]: is this an incomplete sentence?

File: components/data-table/private/header-cell.jsx [hunk 3]
```diff
@@ -172,7 +182,17 @@ const DataTableHeaderCell = createReactClass({
 						) : null}
 					</a>
 				) : (
-					<div className="slds-truncate">{label}</div>
+					<div
+						className={classNames(
+							{
+								// Adds padding to header cells if the are not sortable, but are in a fixed layour / advanced table.
```
Comment (garygong) [inline components/data-table/private/header-cell.jsx]: layout

File: components/data-table/private/head.jsx [hunk 4]
```diff
@@ -56,10 +56,10 @@ const DataTableHead = createReactClass({
 	render () {
 		return (
 			<thead>
-				<tr className="slds-text-title--caps">
+				<tr className="slds-line-height_reset">
```
Comment (garygong) [inline components/data-table/private/head.jsx]: What's the reason for moving `slds-text-title_caps` down on level?  The SLDS sample has it on the `<tr>`, and `slds-text-title_caps` includes `line-height: 1.25` so we wouldn't need to have `slds-line-height_reset` here?

File: components/data-table/private/header-cell.jsx [hunk 5]
```diff
@@ -122,26 +122,36 @@ const DataTableHeaderCell = createReactClass({
 		const sortDirection = this.props.sortDirection || this.state.sortDirection;
 		const expandedSortDirection =
 			sortDirection === 'desc' ? 'descending' : 'ascending';
-		const ariaSort = isSorted ? expandedSortDirection : null;
+		const ariaSort = isSorted ? expandedSortDirection : 'none';
+		// The following padding styles exist in case you have
+		const thStyle = {
+			paddingLeft: sortable ? '0' : null,
```
Comment (garygong) [inline components/data-table/private/header-cell.jsx]: Maybe I'm missing something, but the `<th>` already has `.slds-table_resizable-col`, which includes 'padding: 0`?

File: components/data-table/private/header-cell.jsx [hunk 6]
```diff
@@ -172,7 +182,17 @@ const DataTableHeaderCell = createReactClass({
 						) : null}
 					</a>
 				) : (
-					<div className="slds-truncate">{label}</div>
+					<div
+						className={classNames(
+							{
+								// Adds padding to header cells if the are not sortable, but are in a fixed layour / advanced table.
+								'slds-p-horizontal_x-small': this.props.fixedLayout,
```
Comment (garygong) [inline components/data-table/private/header-cell.jsx]: It looks like the SLDS sample has its padding coming from `<a class="slds-th__action">`.  I think this is ok for us though since ours isn't clickable, and I couldn't find a sample for this case.  All their advanced tables have clickable header cells.

File: components/data-table/private/head.jsx (hunk 4 above)
Comment (interactivellama) [reply components/data-table/private/head.jsx]: I'm following the spec of the advanced variant. I'm seeing `slds-text-title--caps` on the `th` and `slds-line-height_reset` on the `tr`.

screen shot 2018-05-22 at 3 12 03 pm

**Comment by interactivellama** [comment]
@garygong Code updated.

**Comment by garygong** [comment]
LGTM! But it looks like the build failed.
