### PR TITLE
SLDSDatePicker bug fix: Fixing issue where year picker doesn't show years correctly

### LINKED ISSUE #1504: Year picker in SLDSDatePicker doesn't show year menu items correctly
Component: SLDSDatePicker

Menu items (years) are not showing correctly - (`2...`) making it difficult to select a year.

screen shot 2018-08-13 at 3 33 46 pm

I have a fix in progress.

========================
Thank you for filing an issue!

Please review the [frequently asked questions](faq.md) such as:

* [Why do my icons not show up in IE11?](browser-compatibility.md#internet-explorer-11-support)
* [Why aren't my ES6 imports, icons, styles, or fonts working in Create React App?](create-react-app.md)

Please include in your issue:

* If you are working on the problem. Issues may be closed within 30 days if no one is assigned. Maintainers work on this project 20-30 hours per week and have their own prioritized backlog.
* How to duplicate a bug. Line numbers or code to paste into the documentation site examples is helpful.
* If you are a Salesforce employee. You should also create a duplicate work item in your internal ticket system and link to this issue.
* If you plan to work on a new component. Please propose props after reviewing at newly written components and `docs/codebase-overview.md`.

For Salesforce platform questions, please visit https://success.salesforce.com, https://partners.salesforce.com, or https://salesforce.stackexchange.com

This project uses SLDS markup, but you should submit HTML/CSS issues to https://github.com/salesforce-ux/design-system.

### PR DESCRIPTION
**Pull request by davidlygagnon**
- Fix menu items not showing up correctly
- Fix console warning showing up when selecting menu item
- Set slds-datepicker class on menu item to set correct font size of date picker

Fixes #1504 

### Additional description
screen shot 2018-08-14 at 5 05 15 pm

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/date-picker/private/year-picklist.jsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ const DatepickerYearSelector = createReactClass({
 		const opts = [];
 
 		for (let year = fromYear; year < toYear; year += 1) {
-			opts.push({ label: `${year}`, value: year, id: opts.length });
+			opts.push({ label: `${year}`, value: year, id: String(opts.length) });
```
Comment (interactivellama) [inline components/date-picker/private/year-picklist.jsx]: I just saw this today! I didn't catch it when I updated the Combobox props.

Comment (davidlygagnon) [reply components/date-picker/private/year-picklist.jsx]: yup, cool - no worries :)

**Comment by interactivellama** [comment]
Looks good!
