### PR TITLE
Fixes DataTable fixed layout width prop issue

### LINKED ISSUE #1525: FixedLayout DataTableColumn widths don't actually apply
Repro:

Go to the documentation or storybooks and observe that the <th> never gets the width from the column. Only the <td> gets it. Not sure how this ever worked in any previous version.

From my observations the <td> doesn't actually need the width and the column width is mainly determined by the <th>

Most my application's fixed tables also just lost any sort auto-default sizing when upgrading 0.7.x -> 0.8.x so this may be something to watch out for.

### PR DESCRIPTION
**Pull request by edelgado**
Fixes #1525

### Additional description
Currently, when a simple DataTable with the `fixedLayout` prop won't correctly set the width's of the rendered `<th/>` html elements due to a bug in this code:
```js
style={{ width: width ? { width } : null }}
```
Which is being addressed by replacing it with:
```js
style={width ? { width } : null}
```
---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/data-table/private/header-cell.jsx [hunk 1]
```diff
@@ -183,7 +183,7 @@ const DataTableHeaderCell = createReactClass({
 					'slds-text-title_caps'
 				)}
 				scope="col"
-				style={{ width: width ? { width } : null }}
+				style={width ? { width } : null}
```
Comment (edelgado) [inline components/data-table/private/header-cell.jsx]: This is the actual fix 😅

**Comment by edelgado** [comment]
😊
