### PR TITLE
Remove console warnings from CI

### LINKED ISSUE #2348: Remove console warnings from CI
https://travis-ci.org/salesforce/design-system-react/jobs/592730483

Mocha
```
HeadlessChrome 77.0.3865 (Linux 0.0.0) ERROR LOG: 'Warning: Failed prop type: The prop `combobox` is marked as required in `SLDSGlobalHeaderSearch`, but its value is `undefined`.
    in SLDSGlobalHeaderSearch'
02 10 2019 19:29:37.271:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/global-header/logo.svg
02 10 2019 19:29:37.528:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-01.jpg
WARN LOG: 'Warning: [Design System React] SLDSCarousel is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/carousel'
02 10 2019 19:29:37.536:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-02.jpg
02 10 2019 19:29:37.538:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-03.jpg
02 10 2019 19:29:37.800:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-01.jpg
02 10 2019 19:29:37.802:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-02.jpg
02 10 2019 19:29:37.804:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-03.jpg
02 10 2019 19:29:37.929:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-01.jpg
02 10 2019 19:29:37.931:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-02.jpg
02 10 2019 19:29:37.933:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/carousel/carousel-03.jpg
WARN LOG: 'Warning: [Design System React] SLDSColorPicker is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS.'
ERROR LOG: 'Warning: [Design System React] `label` has reached End-of-Life and has been removed from the API of SLDSRadio. Please update your API. Use `labels.label` instead.Please check the current documentation at: https://react.lightningdesignsystem.com/components/radios#prop-labels'
ERROR LOG: 'Warning: `NaN` is an invalid value for the `%s` css style property.%s', 'left', '
    in div (created by SLDSDialog)
    in SLDSDialog (created by Context.Consumer)
    in LanguageDirection(SLDSDialog) (created by SLDSPopoverTooltip)
    in div (created by SLDSPopoverTooltip)
    in SLDSPopoverTooltip (created by SLDSAppLauncherTile)
    in div (created by TextTruncate)
    in TextTruncate (created by SLDSAppLauncherTile)
    in div (created by SLDSAppLauncherTile)
    in div (created by SLDSAppLauncherTile)
    in SLDSAppLauncherTile
    in SLDSIconSettings (created by WrapperComponent)
    in WrapperComponent'
  SLDSColorPicker
    Popover
      Custom tab
        HSV
          saturation-value grid
            - click sets color using coordinates
ERROR LOG: 'Warning: Each child in a list should have a unique "key" prop.%s%s See https://fb.me/react-warning-keys for more information.%s', '
Check the render method of `Menu`.', '', '
    in span (created by Menu)
    in Menu (created by SLDSCombobox)
    in div (created by SLDSDialog)
    in SLDSDialog (created by Context.Consumer)
    in LanguageDirection(SLDSDialog) (created by SLDSCombobox)
    in div (created by SLDSCombobox)
    in div (created by SLDSCombobox)
    in div (created by SLDSCombobox)
    in div (created by SLDSCombobox)
    in SLDSCombobox (created by OnClickOutside(SLDSCombobox))
    in OnClickOutside(SLDSCombobox) (created by Context.Consumer)
    in LanguageDirection(OnClickOutside(SLDSCombobox)) (created by ComboboxDemoComponent)
    in SLDSIconSettings (created by ComboboxDemoComponent)
    in ComboboxDemoComponent (created by WrapperComponent)
    in WrapperComponent'
ERROR LOG: 'Warning: [Design System React] SLDSPopover requires that prop 'children' is an instance of one of the following components: SLDSButton, a, button. An instance of 'SLDSInnerInput' was given. Please check the current documentation at: https://react.lightningdesignsystem.com/components/popovers'
ERROR LOG: 'Warning: [Design System React] The element that triggers SLDSPopoverTooltip must be tabbable for keyboard users. Elements such as anchor, button, input or a DOM element with tabIndex="0" specified are tabbable.  Please check the current documentation at: https://react.lightningdesignsystem.com/components/tooltips'
ERROR LOG: 'Warning: Failed prop type: Invalid prop `name` of type `boolean` supplied to `SLDSCheckbox`, expected `string`.
    in SLDSCheckbox (created by SLDSDataTableHead)
    in SLDSDataTableHead (created by SLDSDataTable)
    in table (created by SLDSDataTable)
    in div (created by SLDSDataTable)
    in div (created by SLDSDataTable)
    in SLDSDataTable
    in SLDSIconSettings'
ERROR LOG: 'Warning: Received `%s` for a non-boolean attribute `%s`.
If you want to write it to the DOM, pass a string instead: %s="%s" or %s={value.toString()}.
If you used to conditionally omit it with %s={condition && value}, pass %s={condition ? value : undefined} instead.%s', 'false', 'name', 'name', 'false', 'name', 'name', 'name', '
    in input (created by SLDSCheckbox)
    in span (created by SLDSCheckbox)
    in div (created by SLDSCheckbox)
    in div (created by SLDSCheckbox)
    in SLDSCheckbox (created by SLDSDataTableHead)
    in div (created by SLDSDataTableHead)
    in th (created by SLDSDataTableHead)
    in tr (created by SLDSDataTableHead)
    in thead (created by SLDSDataTableHead)
    in SLDSDataTableHead (created by SLDSDataTable)
    in table (created by SLDSDataTable)
    in div (created by SLDSDataTable)
    in div (created by SLDSDataTable)
    in SLDSDataTable
    in SLDSIconSettings'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.'
WARN LOG: 'Warning: [Design System React] SLDSFilter is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/filters'
WARN LOG: 'Warning: [Design System React] SLDSInlineEdit is a deprecated component. Bugfixes can be contributed, but new features and additional alignment with SLDS may be declined. For a multiple input form, please use the pattern located at https://www.lightningdesignsystem.com/components/form-element/#Record-Detail that swaps out a read-only `Input` with a base `Input`. For a single input, please use a `Popover` paired with `<Button	category="utility" iconName="edit" variant="icon" />` as the trigger.'
02 10 2019 19:29:41.365:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/illustrations/empty-state-no-access.svg
WARN LOG: 'Warning: [Design System React] Illustration is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS.'
WARN LOG: 'Warning: [Design System React] SLDSLookup is a deprecated component. Bugfixes can be contributed, but new features and additional alignment with SLDS may be declined. Please use an auto-complete Combobox instead. It is more accessible and closer aligned to SLDS.'
ERROR LOG: 'Warning: Failed prop type: The prop `locations[0].id` is marked as required in `SLDSMap`, but its value is `undefined`.
    in SLDSMap'
ERROR LOG: 'Warning: Expected server HTML to contain a matching <%s> in <%s>.', 'div', 'div'
INFO LOG: 'sinon.reset is deprecated and will be removed from the public API in a future version of sinon.'
WARN LOG: 'Warning: [Design System React] SLDSMenuPicklist is a deprecated component. Bugfixes can be contributed, but new features and additional alignment with SLDS may be declined. Please use an read-only Combobox instead. It is more accessible and closer aligned to SLDS.'
WARN LOG: 'Warning: [Design System React] Notification is a deprecated component. Bugfixes can be contributed, but new features and additional alignment with SLDS may be declined. Please use Alert or Toast in the future. Notications is not the same component in SLDS any longer.'
02 10 2019 19:29:45.651:WARN [web-server]: 404: /base/node_modules/@salesforce-ux/design-system/assets/images/welcome-mat/trailhead_badge@2x.png
```

Jest:
```
console.warn utilities/warning/low-priority-warning.js:18
      Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: Please use an external library for date parsing and internationalization like MomentJS (https://github.com/moment/moment/) instead of the default parser.
 PASS  tests/story-based-tests.dom-snapshot-test.js (33.238s)
  ● Console
    console.log tests/story-based-tests.dom-snapshot-test.js:20
      
      ★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★
      QUEUEING: STORY-BASED DOM SNAPSHOT TESTING
      ★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★
      
      EXECUTING /tests/story-based-tests.snapshot-test.js
      BASED ON STORYBOOK STORIES FOUND IN /components/storybook-stories.js
      
      This script uses Jest to call Storyshots 
      https://github.com/storybooks/storybook/tree/next/addons/storyshots on each 
      Storybook story found at http://localhost:9001. This stores a copy of the 
      DOM on load in a text file. If you need an open menu tested, then you will 
      need to open the menu with the `isOpen` prop.
      
      For more information, please review: https://github.com/salesforce/design-system-react/blob/master/tests/README.md
      
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: The prop `expanded` is marked as required in `SLDSAccordionPanel`, but its value is `undefined`.
          in SLDSAccordionPanel (created by AccordionExample)
          in AccordionExample
          in div
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] The element that triggers SLDSPopoverTooltip must be tabbable for keyboard users. Elements such as anchor, button, input or a DOM element with tabIndex="0" specified are tabbable.  Please check the current documentation at: https://react.lightningdesignsystem.com/components/tooltips
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: Invalid prop `required` of type `string` supplied to `SLDSInput`, expected `boolean`.
          in SLDSInput (created by PopoverExample)
          in PopoverExample
          in div
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] SLDSPopover requires that prop 'children' is an instance of one of the following components: SLDSButton, a, button. An instance of 'SLDSPopoverTooltip' was given. Please check the current documentation at: https://react.lightningdesignsystem.com/components/popovers
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: Invalid prop `assistiveText` of type `string` supplied to `SLDSButton`, expected `object`.
          in SLDSButton
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `assistiveText` has reached End-of-Life and has been removed from the API of SLDSButton. Please update your API. `assistiveText` as a string has been deprecated and is now an object to allow for multiple uses in the component. Please use `assistiveText.icon` instead. Please check the current documentation at: https://react.lightningdesignsystem.com/components/buttons#prop-assistiveText
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSInlineEdit is a deprecated component. Bugfixes can be contributed, but new features and additional alignment with SLDS may be declined. For a multiple input form, please use the pattern located at https://www.lightningdesignsystem.com/components/form-element/#Record-Detail that swaps out a read-only `Input` with a base `Input`. For a single input, please use a `Popover` paired with `<Button	category="utility" iconName="edit" variant="icon" />` as the trigger.
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSCarousel is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/carousel
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSColorPicker is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS.
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `label` has reached End-of-Life and has been removed from the API of SLDSRadio. Please update your API. Use `labels.label` instead.Please check the current documentation at: https://react.lightningdesignsystem.com/components/radios#prop-labels
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] The element that triggers SLDSPopoverTooltip must be tabbable for keyboard users. Elements such as anchor, button, input or a DOM element with tabIndex="0" specified are tabbable.  Please check the current documentation at: https://react.lightningdesignsystem.com/components/tooltips
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] The element that triggers SLDSPopoverTooltip must be tabbable for keyboard users. Elements such as anchor, button, input or a DOM element with tabIndex="0" specified are tabbable.  Please check the current documentation at: https://react.lightningdesignsystem.com/components/tooltips
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:102
      Warning: Encountered two children with the same key, `menu-header-my-new-id}`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in ul (created by Menu)
          in Menu (created by SLDSCombobox)
          in div (created by SLDSDialog)
          in SLDSDialog (created by Context.Consumer)
          in LanguageDirection(SLDSDialog) (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in SLDSCombobox (created by OnClickOutside(SLDSCombobox))
          in OnClickOutside(SLDSCombobox) (created by Context.Consumer)
          in LanguageDirection(OnClickOutside(SLDSCombobox)) (created by ComboboxExample)
          in SLDSIconSettings (created by ComboboxExample)
          in ComboboxExample
          in div
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:102
      Warning: Encountered two children with the same key, `menu-header-my-new-id}`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in ul (created by Menu)
          in Menu (created by SLDSCombobox)
          in div (created by SLDSDialog)
          in SLDSDialog (created by Context.Consumer)
          in LanguageDirection(SLDSDialog) (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in div (created by SLDSCombobox)
          in SLDSCombobox (created by OnClickOutside(SLDSCombobox))
          in OnClickOutside(SLDSCombobox) (created by Context.Consumer)
          in LanguageDirection(OnClickOutside(SLDSCombobox)) (created by ComboboxExample)
          in SLDSIconSettings (created by ComboboxExample)
          in ComboboxExample
          in div
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: Invalid prop `name` of type `boolean` supplied to `SLDSCheckbox`, expected `string`.
          in SLDSCheckbox (created by SLDSDataTableHead)
          in SLDSDataTableHead (created by SLDSDataTable)
          in table (created by SLDSDataTable)
          in div (created by SLDSDataTable)
          in div (created by SLDSDataTable)
          in SLDSDataTable (created by DataTableExample)
          in SLDSIconSettings (created by DataTableExample)
          in div (created by DataTableExample)
          in DataTableExample
          in SLDSIconSettings
          in div
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `iconCategory` will be removed in the next major version of SLDSPageHeader. Use `icon` instead. Please check the current documentation at: https://react.lightningdesignsystem.com/components/page-headers#prop-icon
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `iconName` will be removed in the next major version of SLDSPageHeader. Use `icon` instead. Please check the current documentation at: https://react.lightningdesignsystem.com/components/page-headers#prop-icon
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSFilter is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/filters
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `offset` will be removed in the next major version of SLDSPopover. The manual setting of positional offset of dialog components has been deemed unreliable. Position logic has been re-written to deliver better and more reliable positioning. Please create an issue if you have an edge case not covered by the built-in logic. Please check the current documentation at: https://react.lightningdesignsystem.com/components/popovers
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] Illustration is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS.
    console.error node_modules/react/cjs/react.development.js:172
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
          in div
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React]  `components/forms/checkbox` is deprecated. `components/checkbox` should be used. When this path update is made `onChange` event parameters will change from `onChange(value, event, { value }) to `onChange(event, { value }). Please update your event parameters when you change paths.` If you are using the CommonJS named import, `Checkbox` events will break at v1.0 and this warning will be present until then. Please review https://github.com/salesforce/design-system-react/releases when you upgrade. Please check the current documentation at: https://react.lightningdesignsystem.com/components/checkboxes#prop-onChange
    console.error node_modules/warning/warning.js:34
      Warning: [Design System React] `label` has reached End-of-Life and has been removed from the API of SLDSCheckbox. Please update your API. Use `labels.label` instead.Please check the current documentation at: https://react.lightningdesignsystem.com/components/checkboxes#prop-labels
 PASS  components/panel/__tests__/filtering.dom-snapshot-test.jsx
  ● Console
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSPanel is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/panels
    console.warn utilities/warning/low-priority-warning.js:18
      Warning: [Design System React] SLDSFilter is a prototype. (a) Props may change within a minor release. (b) Web Content Accessibility Guidelines may not be met. (c) CSS imports may be required, since it is being added to SLDS. Please check the current documentation at: https://react.lightningdesignsystem.com/components/filters
```

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #2348

Took a while to finish this one up, but it looks much better in both the browser test console and terminal now that it's done!

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/combobox/__examples__/dialog.jsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /* eslint-disable no-console, react/prop-types */
 import React from 'react';
-import Checkbox from '~/components/forms/checkbox';
+import Checkbox from '~/components/checkbox';
```
Comment (interactivellama) [inline components/combobox/__examples__/dialog.jsx]: This will still import the checkbox with the old parameter on the website since the default export still uses  `~/components/forms/checkbox`.

File: components/combobox/private/menu.jsx [hunk 2]
```diff
@@ -451,7 +455,7 @@ const Menu = (props) => {
 			item = React.cloneElement(
 				props.tooltipMenuItemDisabled,
 				tooltipProps,
-				menuItem[props.variant]
+				React.cloneElement(menuItem[props.variant], { tabIndex: 0 })
```
Comment (interactivellama) [inline components/combobox/private/menu.jsx]: `tabIndex: 0` should not be in menu items

File: components/filter/index.jsx [hunk 3]
```diff
@@ -239,7 +239,7 @@ class Filter extends React.Component {
 				)}
 			>
 				{!this.props.isLocked && (this.props.children || this.props.popover) ? (
-					<Popover {...popoverProps}>
+					<Popover {...popoverProps} silenceDeprecatedPropertyWarning>
```
Comment (interactivellama) [inline components/filter/index.jsx]: This is internal. Why is there a deprecated prop in use? Should the deprecated prop be removed from an example?

File: components/menu-dropdown/__docs__/storybook-stories.jsx [hunk 4]
```diff
@@ -134,6 +134,7 @@ const getDropdownPositioned = (props) => {
 		positionedDropdowns.push(
 			<div
 				className="slds-col slds-size_1-of-3"
+				key={`positioned-dropdoown-${position.replace(' ', '')}`}
```
Comment (interactivellama) [inline components/menu-dropdown/__docs__/storybook-stories.jsx]: typo: `dropdoown`

Comment (kevinparkerson) [reply components/menu-dropdown/__docs__/storybook-stories.jsx]: This is what I was talking about with my keyboard having messed up "I" and "O" keys that sometimes duplicate the inputs 😆

File: components/filter/index.jsx (hunk 3 above)
Comment (kevinparkerson) [reply components/filter/index.jsx]: I made sure the `silence{WarningType}` stuff was never included in any examples shown on the site. In nearly all cases, our storybook stories or browser tests are still testing the deprecated features or components, hence the need for silencing. This is the only exception and I wasn't quite sure what to do with it... check this out:

```
const defaultPopoverProps = {
	ariaLabelledby: `${this.getId()}-popover-heading`,
	align: this.props.align,
	body: popoverBody,
	heading: '',
	id: this.getId(),
	isOpen: this.state.popoverIsOpen,
	// MAGIC NUMBERS - REMOVE/REDESIGN WHEN DESIGN FOR RIGHT-ALIGNED FILTERS ARE ADDED TO SLDS
	offset: this.props.align === 'right' ? '0px -35px' : undefined,
	onClose: this.handleClose,
	onRequestClose: this.handleClose,
	position: 'overflowBoundaryElement',
	triggerClassName: 'slds-grow',
};
```

The `offset` value has a note on it in regards to updating this. @interactivellama, are you aware if that has happened yet? Either way, `offset` seems critically important to the functionality here for the time being. I figured disabling the warning was acceptable since our own component is using it (hence it wouldn't be seen by developers) and we could create a separate issue to figure out how to make this work better without offset later.

File: components/combobox/__docs__/__snapshots__/storybook-stories.storyshot [hunk 5]
```diff
@@ -1682,6 +1682,7 @@ exports[`DOM snapshots SLDSCombobox Base Menu Item Disabled With Tooltip Open 1`
                         "cursor": "default",
                       }
                     }
```
[the remark this answers is not in the document]
Comment (kevinparkerson) [reply components/combobox/__docs__/__snapshots__/storybook-stories.storyshot]: I was solving this error:
`Warning: [Design System React] The element that triggers SLDSPopoverTooltip must be tabbable for keyboard users. Elements such as anchor, button, input or a DOM element with tabIndex="0" specified are tabbable.`
How would a tooltip be appropriately accessible if the trigger is not tabbable?

File: components/combobox/private/menu.jsx (hunk 2 above)
Comment (kevinparkerson) [reply components/combobox/private/menu.jsx]: Related to my comment above on accessible tooltips.

File: components/combobox/__examples__/dialog.jsx (hunk 1 above)
Comment (kevinparkerson) [reply components/combobox/__examples__/dialog.jsx]: Need clarification on this one

File: components/combobox/__docs__/__snapshots__/storybook-stories.storyshot (hunk 5 above)
[the remark this answers is not in the document]
Comment (interactivellama) [reply components/combobox/__docs__/__snapshots__/storybook-stories.storyshot]: `aria-selected` connects the focus of the input with the faux highlight on the menu--that's how for instance a screen reader know when menu item you are on.

File: components/combobox/__examples__/dialog.jsx (hunk 1 above)
Comment (interactivellama) [reply components/combobox/__examples__/dialog.jsx]: Until we make a 1.0 release, this needs to stay due to the default export from `index.js` being used on the website examples. That said, we could update the website examples to use the checkbox with the newer parameter order.

Comment (kevinparkerson) [reply components/combobox/__examples__/dialog.jsx]: The default export was changed in release 0.10.11 to `/components/checkbox`. We will need to notify consumers about this potential shift if they were using the default export, instructing them to either use `/components/form/checkbox` or update to utilize the standardized event / object parameter order.
