### PR TITLE
Data table fixed header

### LINKED ISSUE #676: Add Support for Data Table Scrolling
I'd like to add support for data table scrolling. Below is an example. In this example the table header remains visible at all times. The example also shows horizontal scrolling because the table is too wide.

image

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #676

Adds scrolling support for data tables (advanced fixedLayout only).

This is a progress PR as I still need to:
- ~~Fix a tiny 1px visibility with the thead~~
- ~~Figure out what's going on with the initial scrolling and rendering~~
- ~~Write tests~~

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

File: components/data-table/index.jsx [hunk 1]
```diff
@@ -240,6 +268,57 @@ class DataTable extends React.Component {
...
+				theadRef: this.theadRef,
+			});
+		} else if (this.theadRef) {
+			let documentScrollLeft = 0;
+
+			if (document && document.documentElement) {
+				documentScrollLeft = document.documentElement.scrollLeft;
+			}
+
+			this.theadRef.querySelectorAll('th').forEach((column) => {
```
Comment (interactivellama) [inline components/data-table/index.jsx]: `theadRefs` should probably be an array of DOM refs. `querySelectorAll` will work, but I would feel better about using the framework and pushing refs into an array on render and not querying the DOM. This code will also promotes creators of custom callbacks to query inside the component's DOM, too.

I'd recommend passing down a function to header sub component that will update the instance property in the grandparent (`index.jsx`) on render of the header.

File: components/data-table/index.jsx [hunk 2]
```diff
@@ -240,6 +268,57 @@ class DataTable extends React.Component {
...
+				const columnLeft =
+					column.getBoundingClientRect().left + documentScrollLeft;
+				let wrapperLeft = 0;
+
+				if (this.scrollerRef) {
+					wrapperLeft =
+						this.scrollerRef.getBoundingClientRect().left + documentScrollLeft;
+				}
+
+				const cellFixed = column.querySelector('.slds-cell-fixed');
```
Comment (interactivellama) [inline components/data-table/index.jsx]: maybe `theadRefs` needs to be an array of objects.

File: components/data-table/index.jsx [hunk 3]
```diff
@@ -371,6 +455,29 @@ class DataTable extends React.Component {
 				</tbody>
 			</table>
 		);
+
+		if (this.props.fixedHeader) {
+			return (
```
Comment (interactivellama) [inline components/data-table/index.jsx]: This is a little nit-picky, but remove double return exits from the function to increase readability and use something like a `let` instead. I'm open to ternary return, too.

File: components/data-table/index.jsx [hunk 4]
```diff
@@ -309,13 +419,21 @@ class DataTable extends React.Component {
 			ariaProps['aria-multiselectable'] = 'true';
 		}
 
-		return (
+		// This guarantees there are never any old header references if props change
+		this.headerRefs = {
+			action: RowActions ? this.headerRefs.action : [],
```
Comment (interactivellama) [inline components/data-table/index.jsx]: Good call on adding these!
